title: Jahnavi Kachhia
description: AI product leader in healthcare and applied machine learning across research, reviewing, and public speaking.

url: "https://jahnavik186.github.io"
baseurl: ""

nav:
  - title: About
    url: /about/
  - title: Publications
    url: /publications/
  - title: Speaking
    url: /speaking/
  - title: Service
    url: /service/
  - title: Media
    url: /media/

profiles:
  scholar: "https://scholar.google.com/citations?user=bWMslkYAAAAJ&hl=en"
  github: "https://github.com/jahnavik186"
  docker: "https://hub.docker.com/u/jahnavik186"
  linkedin: "https://www.linkedin.com/in/jk186/"
  researchgate: "https://www.researchgate.net/profile/Jahnavi-Kachhia-2?ev=hdr_xprf"
  orcid: "https://orcid.org/my-orcid?orcid=0009-0000-5870-5132"
  scholar_citations: "64"
  scholar_articles: "10"
  github_repositories: "6"
  github_total_forks: "105"
  github_following: "0"
  github_stars: "2"
analytics:
  ga4: "G-0J6QQ8KBE7"

plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty
