title: Jahnavi Kachhia
description: AI product leader in healthcare and applied machine learning across research, reviewing, and public speaking.

url: "https://jahnavik186.github.io"
baseurl: ""

nav:
  - title: About
    url: /about/
  - title: Publications
    url: /publications/
  - title: Speaking
    url: /speaking/
  - title: Service
    url: /service/
  - title: Media
    url: /media/

profiles:
  scholar: "https://scholar.google.com/citations?user=bWMslkYAAAAJ&hl=en"
  github: "https://github.com/jahnavik186"
  docker: "https://hub.docker.com/u/jahnavik186"
  linkedin: "https://www.linkedin.com/in/jk186/"
  scholar_citations: "43"
  scholar_articles: "10"
  github_repositories: "5"
analytics:
  ga4: "G-0J6QQ8KBE7"

plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty
