title: Jahnavi Kachhia
description: AI product leader in healthcare and applied machine learning across research, reviewing, and public speaking.

url: "https://jahnavik186.github.io"
baseurl: ""

nav:
  - title: About
    url: /about/
  - title: Publications
    url: /publications/
  - title: Speaking
    url: /speaking/
  - title: Service
    url: /service/
  - title: Media
    url: /media/

profiles:
  scholar: "https://scholar.google.com/citations?user=bWMslkYAAAAJ&hl=en"
  github: "https://github.com/jahnavik186"
  docker: "https://hub.docker.com/u/jahnavik186"
  docker_repositories: "https://hub.docker.com/repositories/jahnavik186"
  kaggle: "https://www.kaggle.com/jahnavikachhia23"
  academia: "https://abbott.academia.edu/JahnaviKachhia"
  linkedin: "https://www.linkedin.com/in/jk186/"
  researchgate: "https://www.researchgate.net/profile/Jahnavi-Kachhia-2?ev=hdr_xprf"
  orcid: "https://orcid.org/my-orcid?orcid=0009-0000-5870-5132"
  scholar_citations: "174"
  scholar_articles: "11"
  github_repositories: "10"
  github_followers: "61"
  github_profile_repositories: "10"
  github_profile_followers: "61"
  github_total_forks: "152"
  docker_images: "3"
  docker_downloads: "154K"
  kaggle_dataset_rank: "66/9,606"
  kaggle_dataset_percentile: "top 1%"
  github_following: "0"
  github_stars: "2"
analytics:
  ga4: "G-0J6QQ8KBE7"

plugins:
  - jekyll-feed

markdown: kramdown
permalink: pretty
